### ISSUE TITLE
Transport interface and option

### ISSUE THREAD

**Issue by gsouf** [juliangut/spiral#1]
Figuring out that in the doc you are mentioning ``setOptions`` on the ``Transport`` but the [transport interface](https://github.com/juliangut/spiral/blob/master/src/Transport.php) does not define option access. 

That's an issue if I want to work with options of an user implemented transport, the option method might not exist.

Is the transport interface even useful ?

**Comment by juliangut** [comment]
Hi

the original idea was to allow others to implement their own transport class and so I moved the `setOption`, `hasOption`, etc out from the Transport Interface so it won't force you to use only cURL
In the end I ended up deciding to use only cURL implementations (as it is stated in the project description: PSR7 aware cURL client) and so you can see here https://github.com/juliangut/spiral/blob/master/src/Client.php#L49 the client directly sets a cURL option

I agree with you the *Option(s) methods should be included in Transport interface to make it really useful, Option interface is truly transport agnostic so why not fully use it?

I'll give it a twist

**Comment by gsouf** [comment]
I see the issue. I spotted other problems and missing curl options that make it not possible for me to use the library, would you accept some PR with some refactoring?

**Comment by juliangut** [comment]
PRs are always welcome :smiley:

**Comment by gsouf** [comment]
Well, would you accept to remove the transport interface to make things simpler? After all, as you said is primarily a curl client and I doubt that it will be needed to implement curl transport in an other way
