### ISSUE TITLE
0.4 release

### ISSUE THREAD

**Issue by trendfischer** [juliangut/spiral#12]
I'd just like to ask for the roadmap of the 0.4 release. We want to integrate spiral with composer in our application and we need the last commits for our application to work properly.

**Comment by juliangut** [comment]
There is not really a roadmap, I was working with the project the way it was before

I would fix [the minimal coverage decrease](https://coveralls.io/builds/11443173/source?filename=src%2FTransport%2FCurl.php#L166) and it'd be set for 0.4

**Comment by trendfischer** [comment]
Since the release 0.4 is out and my tests were successful, I close this issue. Thanks for the release by the way.
