### ISSUE TITLE
Http redirect and response headers

### ISSUE THREAD

**Issue by gsouf** [juliangut/spiral#3]
Response headers are invalid in case of a http redirect. Actually the headers of all request are concatened together.

e.g calling the following url : ``http://httpbin.org/redirect-to?url=get`` will produce the following headers in the curl response:

```
HTTP/1.1 302 FOUND
Server: nginx
Date: Tue, 09 Feb 2016 11:54:35 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 0
Connection: keep-alive
Location: get
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

HTTP/1.1 200 OK
Server: nginx
Date: Tue, 09 Feb 2016 11:54:35 GMT
Content-Type: application/json
Content-Length: 262
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
```

When ``spiral`` parses the headers it should only take the last set of headers. but it does not. Instead it takes all the headers and if a header is present in some header set, the latest replaces the oldest. But if some headers are present in the oldest header set but not in the latest, it will reside in the response.

See the headers for the returned response for the previous url and note the **Location** header that should not be there:

```
array(8) {
  ["Content-Type"]=>
  array(1) {
    [0]=>
    string(16) "application/json"
  }
  ["Content-Length"]=>
  array(1) {
    [0]=>
    string(3) "262"
  }
  ["Server"]=>
  array(1) {
    [0]=>
    string(5) "nginx"
  }
  ["Date"]=>
  array(1) {
    [0]=>
    string(29) "Tue, 09 Feb 2016 12:00:52 GMT"
  }
  ["Connection"]=>
  array(1) {
    [0]=>
    string(10) "keep-alive"
  }
  ["Location"]=>
  array(1) {
    [0]=>
    string(3) "get"
  }
  ["Access-Control-Allow-Origin"]=>
  array(1) {
    [0]=>
    string(1) "*"
  }
  ["Access-Control-Allow-Credentials"]=>
  array(1) {
    [0]=>
    string(4) "true"
  }
}
```

**Comment by gsouf** [comment]
that's all here https://github.com/juliangut/spiral/blob/da45ca6f7bf42d55d74301ef51a8da9c654b88dc/src/Client.php#L117

and I see 2 possible fixes. Either start parsing header from the last header set or reset the header array when we find the status code line.

**Comment by gsouf** [comment]
Additionally, as mentioned here http://stackoverflow.com/questions/8172323/multiple-redirect-headers#answer-14559787 a redirected request can contain body of previous request. This case is probably very rare, but should be considered

**Comment by juliangut** [comment]
Changed, header blocks get discarded but the last one

**Comment by juliangut** [comment]
Your previous example is added as a test in ClientTest, closing
