### ISSUE TITLE
Curl error is not a server error

### ISSUE THREAD

**Issue by gsouf** [juliangut/spiral#4]
Reading the following: https://github.com/juliangut/spiral/blob/0.1.1/src/Client.php I understand that having a CURL error will lead to a 500 error. But that's a real mistake. Because a Curl error is not a server error. 

Server error means that the server was reached and returned a "valid" error. 

Here the error can be for instance 
- the network that does not work
- an invalid proxy connection
- an invalid url
- a timeout
- too many redirect
- ...

Well, in my opinion that should only return an exception with possibly some additional logic depending on the error type. For instance in my code I will return a proxy exception if the error code matches CURLE_COULDNT_RESOLVE_PROXY

**Comment by juliangut** [comment]
cURL errors are transformed into TransportException with an extra parameter 'category' to hold type of cURL error (FTP, SSL, proxy, ...)
This exceptions are allowed to bubble up out of client (after closing cURL connection) so can be handled on the caller. Now it is the caller's duty to assign HTTP error code if needed

**Comment by juliangut** [comment]
@gsouf if you already have a list of categories for cURL errors it would be nice if you could add them
