### ISSUE TITLE
post_multipart flag is ignored

### ISSUE THREAD

**Issue by Hornwitser** [juliangut/spiral#7]
The value for the `post_multipart` flag is ignored when making a request, and the multipart/form-data format is always used for POST data in a request.

Looks like this is caused by the `$vars` variable being used instead of `$properties` in [Transport/Curl.php:151](https://github.com/juliangut/spiral/blob/d1d035c9ba02de7281451979a9963df093f5c787/src/Transport/Curl.php#L151)

**Comment by juliangut** [comment]
Sorry @Hornwitser this issue fell under my radar and I've just noticed it.

You are right $properties is the correct variable to use.

Could you create a PR to fix this and I'll approve ASAP?

**Comment by juliangut** [comment]
Fixed
