### ISSUE TITLE
HTTP Keep-alive support

### ISSUE THREAD

**Issue by trendfischer** [juliangut/spiral#8]
I am searching for a PSR7-Transport lib and found this. Since I have to send requests against an HTTPS-API I am interested to use the CURL Keep-alive feature to avoid around 10ms connection time due to SSL negotiation for each request.

So I wonder, if in src/Transport/Curl.php the `$this->close()` in the request()-Method could be removed to keep the handle active? Or is there any bad experience with curl to avoid such a behavior?
If not I'd like to test this lib and send a pull request eventually, if it works with my application.

**Comment by juliangut** [comment]
Hi @trendfischer, as far as I can see there is no problem with keeping connection open.

In case on a connection error [closing the connection](https://github.com/juliangut/spiral/blob/master/src/Transport/Curl.php#L167) seems like the natural way to go. But I've noticed this is done [on Client class](https://github.com/juliangut/spiral/blob/master/src/Client.php#L93) as well

It could be removed from transport and customized on Client by setting an attribute (closeOnError??) and letting the user catch the bubbled exception. In this scenario the end user would be responsible of `$client->getTransport()->close()` which doesn't look nice

Feel free to PR!

**Comment by juliangut** [comment]
@trendfischer I've made the change and added closeOnError attribute to Client, defaults to true. Thanks for the suggestion

**Comment by trendfischer** [comment]
Added two missed `close()` calls to my PR. I had to combine it with my PSR7-Body issues, cause without the patch, I could not test it in my application.

**Comment by juliangut** [comment]
Still not fixed

**Comment by juliangut** [comment]
Fixed
